In [4]:
import numpy as np
a=np.arange(12).reshape(4,3)
print('prer',a)
np.random.shuffle(a)
print('neweqwe',a)

prer [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
neweqwe [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 0  1  2]]


In [1]:
import tensorflow

In [2]:
import keras

In [5]:
import sklearn.tree as skt


In [6]:
# importing tensorflow 
import tensorflow as tf 

# creating nodes in computation graph 
node1 = tf.constant(3, dtype=tf.int32) 
node2 = tf.constant(5, dtype=tf.int32) 
node3 = tf.add(node1, node2) 

# create tensorflow session object 
sess = tf.Session() 

# evaluating node3 and printing the result 
print("Sum of node1 and node2 is:",sess.run(node3)) 

# closing the session 
sess.close() 


AttributeError: module 'tensorflow' has no attribute 'Session'

In [7]:
import tensorflow as tf
msg = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(msg))

AttributeError: module 'tensorflow' has no attribute 'Session'

In [1]:
import pandas as pd

In [2]:
pd.__version__

'1.1.4'

In [3]:
import sklearn as sk
print(sk.__version__)

0.23.2


In [2]:
import seaborn


In [3]:
seaborn.__version__

'0.11.1'